CREATE TABLE b_awz_gitmd (
    ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    LINK varchar(256) NOT NULL,
    HASH varchar(64) NOT NULL,
    CREATE_DATE timestamp NOT NULL,
    EXPIRED_DATE timestamp NOT NULL,
    CONTENT text,
    PRIMARY KEY (ID)
);
CREATE INDEX b_awz_dealsproductfield_hash ON b_awz_gitmd (hash);